version: "2"
services:
  grafana:
    build: ./images/grafana
    image: "informatica/grafana:4.4.1"
    hostname: grafana
    restart: on-failure:3  
    networks:
      default:
        ipv4_address: 172.28.15.1
    ports:
      - "3000:3000"

  prometheus:
    image: "prom/prometheus:v1.7.1"
    hostname: prometheus
    restart: on-failure:3
    networks:
      default:
        ipv4_address: 172.28.15.2
    ports:
      - "9090:9090"
    volumes:
      - metrics_data:/prometheus

networks:
    default:
      ipam:
        config:
          - subnet: 172.28.0.0/16

# External volumes created by scripts, used for persisting 
# metrics data outside of docker-compose lifecycle
volumes:
    metrics_data:
        external: true